/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package quiz_game;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author gaurav_verma
 */
public class Quiz_game_design1 extends javax.swing.JFrame {

    /**
     * Creates new form add_ques
     */
    
    String player_name;
    String q_type,q_level;
    int id_counter=0;
    
    int radio_flag=0;
    
     int total_Attempt=0;
     int total_not_attempt=0;
     int correct=0;
     int wrong=0;
     int qus_counter=0;
    
    //int id[];
    ArrayList<Integer> id=new ArrayList<>();
    ArrayList<String> ans=new ArrayList<>();
    
    public Quiz_game_design1(String player_name,String q_type,String q_level) 
    {
        this.player_name=player_name;
        this.q_type=q_type;
        this.q_level=q_level;  
        
        initComponents();
        jLabel2.setText(q_type);
        jLabel3.setText(q_level);
        
        getId();
        verify();
        showQues2(id.get(id_counter));
    }

    
//    private void showQues1()
//    {
//            showQues2(id.get(id_counter));
//    }
    
    
    private void verify()
    {
      if(id.size()==0)
      {
          JOptionPane.showMessageDialog(null," This quiz not ready yet ...!!! ");
          dispose();
          new Add_ques_design1(player_name).setVisible(true);
      }
    }
    
    private void getAns()
    {
        String player_ans="";
        String correct_ans="";
        int local_flag=0;
        
        if(id_counter<id.size())
        {
            correct_ans=ans.get(id_counter);
        }
        
        
        if(jRadioButton1.isSelected())
        {
            player_ans="OPTION A";
            local_flag=1;
        }
        else if(jRadioButton2.isSelected())
        {
            player_ans="OPTION B";
            local_flag=1;
        }
        else if(jRadioButton3.isSelected())
        {
            player_ans="OPTION C";
            local_flag=1;
        }
        else if(jRadioButton4.isSelected())
        {
            player_ans="OPTION D";
            local_flag=1;
        }
        else
        {
            total_not_attempt++;
        }
        
        if(local_flag==1)
        {
            if(player_ans.equals(correct_ans))
            {
              correct++;
              total_Attempt++;
              System.out.println("ok --> "+correct+" attempt --> "+total_Attempt+" not attempt --> "+total_not_attempt);
              local_flag=0;
            }
            else
            {
              wrong++;  
              total_Attempt++;
              System.out.println("not ok --> "+wrong+" attempt --> "+total_Attempt+" not attempt --> "+total_not_attempt);
            }
        }
        
        id_counter++;
    }
    
    private void showQues2(int q_id)
    {
        
        buttonGroup1.clearSelection();
        
        try
        {
            Connection con=joint_login.DB.my_DB();
            PreparedStatement pstmt = con.prepareStatement("select * from my_ques_work where `q_id`=?");
            pstmt.setInt(1,q_id);
            ResultSet rs=pstmt.executeQuery();
            
            if(rs.next())
            {
                jTextArea1.setText(rs.getString("ques"));
                jTextField2.setText(rs.getString("option_a"));
                jTextField3.setText(rs.getString("option_b"));
                jTextField4.setText(rs.getString("option_c"));
                jTextField5.setText(rs.getString("option_d"));
            }
            else
            { JOptionPane.showMessageDialog(null,"q_id not found --> "); }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error is --> "+e);
        }
    }   
    
    private void getId()
    {   
        try
        {
            Connection con=joint_login.DB.my_DB();
            PreparedStatement pstmt = con.prepareStatement("select * from my_ques_work where `type`=? and `level`=?");
            pstmt.setString(1,q_type);
            pstmt.setString(2,q_level);
            
            ResultSet rs=pstmt.executeQuery();
            
            while(rs.next())
            {
            id.add(rs.getInt("q_id"));
            ans.add(rs.getString("ans"));
            }
            
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error is --> "+e);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 0, 110, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField2.setEditable(false);
        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(220, 320, 250, 40);

        jTextField5.setEditable(false);
        jTextField5.setText("jTextField5");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(700, 410, 240, 40);

        jTextField3.setEditable(false);
        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(700, 320, 240, 40);

        jLabel11.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel11.setText("Quiz   :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(210, 90, 100, 30);

        jTextField4.setEditable(false);
        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(220, 410, 250, 40);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(10);
        jTextArea1.setRows(3);
        jTextArea1.setText("jTextArea1");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 160, 720, 100);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton3.setText("OPTION  C");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(80, 410, 130, 35);

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(730, 90, 150, 30);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 90, 200, 30);

        jLabel5.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel5.setText("Level   :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 90, 90, 30);

        jButton1.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jButton1.setText("Submit  And  Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 510, 870, 50);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel1.setText("Quiz Time");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 20, 200, 60);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel4.setText("QUESTION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 200, 72, 19);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton1.setText("OPTION  A");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(80, 320, 130, 40);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton4.setText("OPTION  D");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(540, 410, 130, 35);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jRadioButton2.setText("OPTION  B");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(540, 320, 130, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        id.clear();
        ans.clear();
        id_counter=0;
        dispose();
        new Add_ques_design1(player_name).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        getAns();
        System.out.println("qus_counter is --> "+qus_counter);
        
//        if(id.size()<=10)
//        {
            if(id_counter<id.size())
            {
                showQues2(id.get(id_counter));
                qus_counter++;
            }
//        }
        else
        {
            JOptionPane.showMessageDialog(null,"All Questions Attempted. Press OK to see Result..");
            
            System.out.println(total_not_attempt+" "+total_Attempt+" "+correct+" "+wrong);
            
            dispose();
            new result(q_type,q_level,player_name,total_not_attempt,total_Attempt,correct,wrong).setVisible(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz_game_design1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz_game_design1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz_game_design1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz_game_design1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz_game_design1("","","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}